name: fast_develop
description: This is a rapid development library that encapsulates some commonly used methods. Use fast_router in conflict with fluro
version: 2.0.4+1
homepage: https://github.com/StrangerKjq/fast_develop

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  # https://pub.flutter-io.cn/packages/fast_mvvm
  fast_mvvm: ^2.0.4
  fast_router: ^2.0.1+1

  # Flutter 轮播图 https://pub.flutter-io.cn/packages/flutter_swiper
  flutter_swiper_null_safety: ^1.0.0
  #  一个适用于iOS和Android的Flutter插件，用于从图像库中拾取图像，并使用相机拍摄新照片。
  #  https://pub.flutter-io.cn/packages/image_picker
  image_picker: ^0.7.4
  # 图片缓存 https://pub.flutter-io.cn/packages/cached_network_image
  cached_network_image: ^3.0.0
  # https://pub.flutter-io.cn/packages/url_launcher
  url_launcher: ^6.0.3
  # 本地json对象存储 https://pub.flutter-io.cn/packages/localstorage
  localstorage: ^4.0.0+1
  #  https://pub.flutter-io.cn/packages/flutter_screenutil
  flutter_screenutil: ^5.0.0
  #  https://pub.flutter-io.cn/packages/flutter_easyrefresh
  flutter_easyrefresh: ^2.2.0
  # https://pub.flutter-io.cn/packages/package_info
  package_info: ^2.0.0
  # https://pub.flutter-io.cn/packages/dio
  dio: ^4.0.0
  dio_cookie_manager: ^2.0.0
  dio_http2_adapter: ^2.0.0

  # https://pub.flutter-io.cn/packages/universal_io
  universal_io: ^2.0.4
  # https://pub.flutter-io.cn/packages/device_info
  device_info: ^2.0.0
  # State https://pub.flutter-io.cn/packages/provider
  provider: ^5.0.0
  #https://pub.flutter-io.cn/packages/convert
  convert: ^3.0.0
  #https://pub.flutter-io.cn/packages/crypto
  crypto: ^3.0.1
  # https://pub.flutter-io.cn/packages/cropƒ
  crop: ^0.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
