name: fast_develop
description: A new fast develop package.
version: 1.1.2+4
author: kang_1994@outlook.com
homepage: https://github.com/StrangerKjq/fast_develop

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  # https://pub.flutter-io.cn/packages/fast_mvvm
  fast_mvvm: ^1.2.0+2

  fast_router: ^1.0.1

  # Flutter 轮播图 https://pub.flutter-io.cn/packages/flutter_swiper
  flutter_swiper: ^1.1.6
  #  一个适用于iOS和Android的Flutter插件，用于从图像库中拾取图像，并使用相机拍摄新照片。
  #  https://pub.flutter-io.cn/packages/image_picker
  image_picker: ^0.6.7+4
  # 图片缓存 https://pub.flutter-io.cn/packages/cached_network_image
  cached_network_image: ^2.3.1
  # https://pub.flutter-io.cn/packages/cropƒ
  crop: ^0.4.0

  # https://pub.flutter-io.cn/packages/url_launcher
  url_launcher: ^5.5.0

  # 本地json对象存储 https://pub.flutter-io.cn/packages/localstorage
  localstorage: ^3.0.2+5
  #  https://pub.flutter-io.cn/packages/flutter_screenutil
  flutter_screenutil: ^2.3.1

  #  https://pub.flutter-io.cn/packages/flutter_easyrefresh
  flutter_easyrefresh: ^2.1.5
  # https://pub.flutter-io.cn/packages/universal_io
  universal_io: ^1.0.1
  # https://pub.flutter-io.cn/packages/device_info
  device_info: ^0.4.2+4
  # https://pub.flutter-io.cn/packages/package_info
  package_info: ^0.4.1
  # https://pub.flutter-io.cn/packages/dio
  dio: ^3.0.9
  dio_cookie_manager: ^1.0.0
  dio_http2_adapter: ^1.0.0

  convert: ^2.1.1
  crypto: ^2.1.5
  # State https://pub.flutter-io.cn/packages/provider
  provider: ^4.3.1
dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
